// PocketGB — preload: context-isolated IPC bridge
'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pocketgb', {
  openRomDialog: () => ipcRenderer.send('open-rom-dialog'),
  onRomOpened: (cb) => ipcRenderer.on('rom-opened', (e, info) => cb(info)),
  writeSav: (path, u8) => ipcRenderer.send('write-sav', path, u8),
  readSav: (path) => ipcRenderer.invoke('read-sav', path),
  writeState: (path, u8, thumbB64) => ipcRenderer.send('write-state', path, u8, thumbB64),
  readState: (path) => ipcRenderer.invoke('read-state', path),
  readThumbnail: (path) => ipcRenderer.invoke('read-thumbnail', path),
  listStates: (key) => ipcRenderer.invoke('list-states', key),
  deleteRom: (romPath) => ipcRenderer.invoke('delete-rom', romPath),
  deleteSaves: (romPath) => ipcRenderer.invoke('delete-saves', romPath),
  onReset: (cb) => ipcRenderer.on('reset', () => cb()),
  onPause: (cb) => ipcRenderer.on('pause', (e, paused) => cb(paused)),
  onMute: (cb) => ipcRenderer.on('mute', (e, muted) => cb(muted)),
  onForceDmg: (cb) => ipcRenderer.on('force-dmg', (e, on) => cb(on)),
  onSaveState: (cb) => ipcRenderer.on('save-state', (e, slot) => cb(slot)),
  onLoadState: (cb) => ipcRenderer.on('load-state', (e, slot) => cb(slot)),
  onAppQuitting: (cb) => ipcRenderer.on('app-quitting', () => cb()),
  setSetting: (k, v) => ipcRenderer.send('set-setting', k, v),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  openRomPath: (p) => ipcRenderer.send('open-rom-path', p),
  saveFile: (name, b64) => ipcRenderer.invoke('save-file', name, b64),
  saveShot: (key, b64) => ipcRenderer.invoke('save-shot', key, b64),
  listShots: (key) => ipcRenderer.invoke('list-shots', key),
  readShot: (key, file) => ipcRenderer.invoke('read-shot', key, file),
  deleteShot: (key, file) => ipcRenderer.invoke('delete-shot', key, file),
  setCover: (romPath, key, file) => ipcRenderer.invoke('set-cover', romPath, key, file),
  readCover: (romPath, key) => ipcRenderer.invoke('read-cover', romPath, key),
  openShaderPack: () => ipcRenderer.invoke('open-shader-pack'),
  readShaderPack: (path) => ipcRenderer.invoke('read-shader-pack', path),
  onShaderPackChanged: (cb) => ipcRenderer.on('shader-pack-changed', (e, p) => cb(p)),
  linkHost: (port) => ipcRenderer.invoke('link-host', port),
  linkJoin: (port, host) => ipcRenderer.invoke('link-join', port, host),
  linkStop: () => ipcRenderer.invoke('link-stop'),
  linkSend: (b) => ipcRenderer.send('link-send', b),
  onLinkData: (cb) => ipcRenderer.on('link-data', (e, u8) => cb(u8)),
  onLinkStatus: (cb) => ipcRenderer.on('link-status', (e, st) => cb(st)),
  onLinkHosting: (cb) => ipcRenderer.on('link-hosting', (e, port) => cb(port)),
  onLinkError: (cb) => ipcRenderer.on('link-error', (e, msg) => cb(msg)),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (e, text) => cb(text)),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
});
